- name: Test
  hosts:
    - default
  vars:
    ansible_user: claude
    ansible_password: Cyberfull2021
    ansible_connection: winrm
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
  tasks:
    - name: debug
      ansible.builtin.debug:
        msg: toto
    - name: create file
      ansible.builtin.shell:
        cmd: mkidr /foo
    - name: create file
      ansible.builtin.file:
        path: /foo
        state: directory

    - name: create file
      ansible.windows.win_file:
        path: C:\foo.conf
        state: touch
    - name: Donwload java
      ansible.windows.win_get_url:
        url: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=244068_89d678f2be164786b292527658ca1605
        dest: C:\java.exe
        validate_certs: no

    